### ISSUE TITLE
Webmux behind reverse proxy

### ISSUE THREAD

**Issue by ghost** [ronreiter/webmux#4]
Is there way to configre an context path so that I can run webmux in a subdir (like /webmux/)?

**Comment by ronreiter** [comment]
you'll have to add some code for that (Flask), you can send over a pull request.

**Comment by ronreiter** [comment]
why not just add a subdomain?

**Comment by maikeldus** [comment]
I tried to add this, but after some fiddling I couldn't get it working.

I use this on the same domain because I otherwise need to buy another SSL certificate for a subodmain.

**Comment by ronreiter** [comment]
The reverse proxy needs to support websockets.
