### ISSUE TITLE
ImportError: 'twisted'

### ISSUE THREAD

**Issue by ghost** [ronreiter/webmux#8]
Hi,
I done for instructor install. It is okey.
when i am runnig webmuxd on terminal. It shows errors .:
$ webmuxd
Traceback (most recent call last):
  File "/usr/bin/webmuxd", line 3, in <module>
    from webmux.main import main
  File "/usr/lib/python3.5/site-packages/webmux/main.py", line 3, in <module>
    from twisted.internet import reactor
ImportError: No module named 'twisted'
$
(I m using Gnu/Linux -> Fedora 24 , kernel = 4.7.7, python3.5.1)

**Comment by justNik101** [comment]
Ghost, try installing the dependency 
Via
pip3 install twisted
